### ISSUE TITLE
Error in bam2h5.py

### ISSUE THREAD

**Issue by boxiangliu** [bmvdgeijn/WASP#35]
Hello Bryce and Graham,

I am using the CHT to map eQTLs. Step 1 and 4 was completed without any problem. But the last bit of step 5 gives the following error. I could not pinpoint the origin of this error so was wondering if you could give me a pointer. Would be happy to provide example data if needed. Thanks! 

### Begining error message ### 
setting statistics for each chromosome
Traceback (most recent call last):
  File "/srv/persistent/bliu2/tools/WASP/CHT/bam2h5.py", line 696, in <module>
    main()
  File "/srv/persistent/bliu2/tools/WASP/CHT/bam2h5.py", line 684, in main
    chromstat.set_stats(h5f, chrom_list)
  File "/srv/persistent/bliu2/tools/WASP/CHT/chromstat.py", line 100, in set_stats
    chrom_stat.set_from_vals(node[:])
  File "/srv/persistent/bliu2/tools/anaconda/lib/python2.7/site-packages/tables/array.py", line 648, in __getitem__
    arr = self._read_slice(startl, stopl, stepl, shape)
  File "/srv/persistent/bliu2/tools/anaconda/lib/python2.7/site-packages/tables/array.py", line 754, in _read_slice
    self._g_read_slice(startl, stopl, stepl, nparr)
  File "hdf5extension.pyx", line 1491, in tables.hdf5extension.Array._g_read_slice (tables/hdf5extension.c:14091)
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 550, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1872, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2902, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1382, in H5Z_pipeline
    filter returned failure during read
  File "H5Zdeflate.c", line 125, in H5Z_filter_deflate
    inflate() failed

End of HDF5 error back trace

Problems reading the array data.

### End of error message ### 

Bosh

**Comment by gmcvicker** [comment]
Hi Bosh,
The error is coming from the HDF5 library, but I am not sure what is causing it. My best guess is that there was insufficient memory or a problem reading from the disk. Can you try increasing the amount of RAM available (e.g. to something like 8GB or 16GB) and running it again? If that still fails can you send us some example data and your command line?

Graham

**Comment by boshliu** [comment]
Okay. that is good to know! I changed my code slightly and running again. I will let you know!

**Comment by boxiangliu** [comment]
Graham,

Your suggestion resolved the problem. Thank you!
