### ISSUE TITLE
find_intersecting_snps.py encounters IndexError when checking read for ref or alt allele

### ISSUE THREAD

**Issue by anthony-aylward** [bmvdgeijn/WASP#50]
When running `find_intersecting_snps.py`, I got the following output:

```
SAMPLES: ['sample1']
command line: /lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py --is_sorted --output_dir /data/t2d-progenitor/CHIP-seq/PE_HNF6 --snp_tab /data/t2d-progenitor/h5/snp_tab.h5 --snp_index /data/t2d-progenitor/h5/snp_index.h5 --haplotype /data/t2d-progenitor/h5/haplotypes.h5 --samples sample1 /data/t2d-progenitor/CHIP-seq/PE_HNF6/PE_HNF6.sort.bam
prefix: /data/t2d-progenitor/CHIP-seq/PE_HNF6/PE_HNF6.sort
reading reads from:
  /data/t2d-progenitor/CHIP-seq/PE_HNF6/PE_HNF6.sort.bam
writing output files to:
  /data/t2d-progenitor/CHIP-seq/PE_HNF6/PE_HNF6.sort.remap.fq.gz
  /data/t2d-progenitor/CHIP-seq/PE_HNF6/PE_HNF6.sort.keep.bam
  /data/t2d-progenitor/CHIP-seq/PE_HNF6/PE_HNF6.sort.to.remap.bam
starting chromosome chrM
reading SNPs from file '/data/t2d-progenitor/h5/snp_tab.h5'
WARNING: chromosome chrM is not in snp_tab.h5 file, assuming no SNPs for this chromosome
processing reads
starting chromosome chr1
reading SNPs from file '/data/t2d-progenitor/h5/snp_tab.h5'
reducing 344856 SNPs on chromosome chr1 to 214199 positions that are polymorphic in sample of 1 individuals
processing reads
Traceback (most recent call last):
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 930, in <module>
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 909, in main
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 666, in filter_reads
    max_seqs, max_snps)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 801, in process_single_read
    snp_read_pos)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 391, in count_ref_alt_matches
    if ref_alleles[i] == read.query[read_pos[i]-1]:
IndexError: string index out of range
Closing remaining open files:/data/t2d-progenitor/h5/snp_index.h5...done/data/t2d-progenitor/h5/snp_tab.h5...done/data/t2d-progenitor/h5/haplotypes.h5...done
```

Deducing that the problem occurred in the `count_ref_alt_matches` function, I altered it to print some more information:

```
def count_ref_alt_matches(read, read_stats, snp_tab, snp_idx, read_pos):
    ref_alleles = snp_tab.snp_allele1[snp_idx]
    alt_alleles = snp_tab.snp_allele2[snp_idx]

    for i in range(len(snp_idx)):
        print('read.query: ' + read.query)
        print('len(read.query): ' + str(len(read.query)))
        print('read_pos[i]: ' +  str(read_pos[i]))
        if ref_alleles[i] == read.query[read_pos[i]-1]:
            # read matches reference allele
            read_stats.ref_count += 1
        elif alt_alleles[i] == read.query[read_pos[i]-1]:
            # read matches non-reference allele
            read_stats.alt_count += 1
        else:
            # read matches neither ref nor other
            read_stats.other_count += 1
```

This of course printed many lines as it iterated over reads, but the last few were:

```
read.query: ACACAACTTGCGGAATGCAATAAAATTATTTTGCCACCTCTCCCTTTAAA
len(read.query): 50
read_pos[i]: 28
read.query: CCCCTGGCTTCCACATGCTGAGTTTTCAGTCTCCCATCTCAAAGGCCCCA
len(read.query): 50
read_pos[i]: 13
read.query: CATAAAAAAAAAACAAAAAAAGACTGAAAAATATAGGTAT
len(read.query): 40
read_pos[i]: 41
Traceback (most recent call last):
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 933, in <module>
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 912, in main
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 669, in filter_reads
    max_seqs, max_snps)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 804, in process_single_read
    snp_read_pos)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 394, in count_ref_alt_matches
    if ref_alleles[i] == read.query[read_pos[i]-1]:
IndexError: string index out of range
Closing remaining open files:/data/t2d-progenitor/h5/snp_index.h5...done/data/t2d-progenitor/h5/snp_tab.h5...done/data/t2d-progenitor/h5/haplotypes.h5...done
```

It seems the error occurs because the distance from the beginning of the read to the variant is longer than the total length of the read. I suspect this is not an issue with my data, because a previous version of `find_intersecting_snps.py` (pre- Sept. 3) handled this input file without errors. I'm curious about how you think this situation should be handled.

**Comment by anthony-aylward** [comment]
I saw the same issue again with a paired-end input file:
```
read.query: TCTCTAAACTGAATATTCTGGTTATCAGCTACTGTGTTCTTTTATGATTTTTAGCTTCTTGCATTAAGTTAAAACTGCTCCTTTAGCTCAGA
len(read.query): 92
read_pos[i]: 29
read.query: TCTCTAAACTGAATATTCTGGTTATCAGCTACTGTGTTCTTTTATGATTTTTAGCTTCTTGCATTAAGTTAAAACTGCTCCTTTAGCTCAGA
len(read.query): 92
read_pos[i]: 87
read.query: TCTCTAAACTGAATATTCTGGTTATCAGCTACTGTGTTCTTTTATGATTTTTAGCTTCTTGCATTAAGTTAAAACTGCTCCTTTAGCTCAGA
len(read.query): 92
read_pos[i]: 92
read.query: TCTCTAAACTGAATATTCTGGTTATCAGCTACTGTGTTCTTTTATGATTTTTAGCTTCTTGCATTAAGTTAAAACTGCTCCTTTAGCTCAGA
len(read.query): 92
read_pos[i]: 100
Traceback (most recent call last):
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 933, in <module>
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 912, in main
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 654, in filter_reads
    max_snps)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 705, in process_paired_read
    snp_read_pos)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 394, in count_ref_alt_matches
    if ref_alleles[i] == read.query[read_pos[i]-1]:
IndexError: string index out of range
Closing remaining open files:/data/t2d-progenitor/h5/snp_index.h5...done/data/t2d-progenitor/h5/snp_tab.h5...done/data/t2d-progenitor/h5/haplotypes.h5...done
```

**Comment by gmcvicker** [comment]
Hi Anthony, I will look into this problem. Is if possible for you to share any of your input files with me? If not, perhaps you can provide some additional information about this read. If you could print out read.cigar, that would be helpful. What mapper did you use?

Thanks!

Graham

**Comment by anthony-aylward** [comment]
I can't share these files now but I'll look into it. 

Here's a version with read.cigar printed:
```
read.query: ACACAACTTGCGGAATGCAATAAAATTATTTTGCCACCTCTCCCTTTAAA
['read.cigar: ', (0, 50)]
len(read.query): 50
read_pos[i]: 28
read.query: CCCCTGGCTTCCACATGCTGAGTTTTCAGTCTCCCATCTCAAAGGCCCCA
['read.cigar: ', (0, 50)]
len(read.query): 50
read_pos[i]: 13
read.query: CATAAAAAAAAAACAAAAAAAGACTGAAAAATATAGGTAT
['read.cigar: ', (4, 10), (0, 40)]
len(read.query): 40
read_pos[i]: 41
Traceback (most recent call last):
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 934, in <module>
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 913, in main
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 670, in filter_reads
    max_seqs, max_snps)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 805, in process_single_read
    snp_read_pos)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 395, in count_ref_alt_matches
    if ref_alleles[i] == read.query[read_pos[i]-1]:
IndexError: string index out of range
Closing remaining open files:/data/t2d-progenitor/h5/snp_tab.h5...done/data/t2d-progenitor/h5/haplotypes.h5...done/data/t2d-progenitor/h5/snp_index.h5...done
```
Maybe this gives some insight into why this read is shorter than the previous ones (40 bp rather than 50)? Most if not all of the successfully processed reads in this example appear to be 50 bp.


In the above example, the mapper I used was `bwa` as:
```
bwa aln -q 15 reference.fasta prefix.fastq > prefix.sai
bwa samse  reference.fasta prefix.sai prefix.fastq > prefix.sam
samtools view -Sbq 30 prefix.sam > prefix.bam
samtools sort -o prefix.sort.bam prefix.bam
samtools index prefix.sort.bam
```

**Comment by gmcvicker** [comment]
From this example it looks like there might be a problem with how soft-clipped reads are being handled. I will investigate further.

**Comment by anthony-aylward** [comment]
I see, perhaps when bases are soft-clipped from the front of a read, it causes the indexing of the read to change. 

Looking at the read.cigar value for other example supports this diagnosis, I think:
```
read.query: CTCCCAAGTAGCTAGGATTACAGGCATGTGCCAACATGCCTGGCTAATTGTTTGTATTTTTAGTAGAGACGGGGTTTCTCCATGTTGGTCAGGCTGGT
['read.cigar: ', (0, 98)]
len(read.query): 98
read_pos[i]: 88
read.query: TCTCTAAACTGAATATTCTGGTTATCAGCTACTGTGTTCTTTTATGATTTTTAGCTTCTTGCATTAAGTTAAAACTGCTCCTTTAGCTCAGA
['read.cigar: ', (4, 8), (0, 75), (2, 1), (0, 17)]
len(read.query): 92
read_pos[i]: 29
read.query: TCTCTAAACTGAATATTCTGGTTATCAGCTACTGTGTTCTTTTATGATTTTTAGCTTCTTGCATTAAGTTAAAACTGCTCCTTTAGCTCAGA
['read.cigar: ', (4, 8), (0, 75), (2, 1), (0, 17)]
len(read.query): 92
read_pos[i]: 87
read.query: TCTCTAAACTGAATATTCTGGTTATCAGCTACTGTGTTCTTTTATGATTTTTAGCTTCTTGCATTAAGTTAAAACTGCTCCTTTAGCTCAGA
['read.cigar: ', (4, 8), (0, 75), (2, 1), (0, 17)]
len(read.query): 92
read_pos[i]: 92
read.query: TCTCTAAACTGAATATTCTGGTTATCAGCTACTGTGTTCTTTTATGATTTTTAGCTTCTTGCATTAAGTTAAAACTGCTCCTTTAGCTCAGA
['read.cigar: ', (4, 8), (0, 75), (2, 1), (0, 17)]
len(read.query): 92
read_pos[i]: 100
Traceback (most recent call last):
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 934, in <module>
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 913, in main
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 655, in filter_reads
    max_snps)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 706, in process_paired_read
    snp_read_pos)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 395, in count_ref_alt_matches
    if ref_alleles[i] == read.query[read_pos[i]-1]:
IndexError: string index out of range
Closing remaining open files:/data/t2d-progenitor/h5/snp_tab.h5...done/data/t2d-progenitor/h5/haplotypes.h5...done/data/t2d-progenitor/h5/snp_index.h5...done
```

**Comment by gmcvicker** [comment]
Hi Anthony, I have committed a fix, which I hope fixes this problem: https://github.com/bmvdgeijn/WASP/commit/a48f02cb7c442656fdc8932144e62f53f416d6dd

Can you pull the latest changes from the master branch and try again?
Thanks,
Graham
