### ISSUE TITLE
find_intersecting_snps.py encounters AttributeError when operating on paired-end reads

### ISSUE THREAD

**Issue by anthony-aylward** [bmvdgeijn/WASP#51]
I've run into a puzzling error when applying `find_intersecting_snps.py` to some paired-end data. The script produces this output:
```
SAMPLES: ['sample1']
command line: /lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py --is_sorted --output_dir /data/t2d-progenitor/ATAC-seq/PE_ATAC --snp_tab /data/t2d-progenitor/h5/snp_tab.h5 --snp_index /data/t2d-progenitor/h5/snp_index.h5 --haplotype /data/t2d-progenitor/h5/haplotypes.h5 --samples sample1 /data/t2d-progenitor/ATAC-seq/PE_ATAC/PE_ATAC.sort.bam --is_paired_end
prefix: /data/t2d-progenitor/ATAC-seq/PE_ATAC/PE_ATAC.sort
reading reads from:
  /data/t2d-progenitor/ATAC-seq/PE_ATAC/PE_ATAC.sort.bam
writing output files to:
  /data/t2d-progenitor/ATAC-seq/PE_ATAC/PE_ATAC.sort.remap.fq1.gz
  /data/t2d-progenitor/ATAC-seq/PE_ATAC/PE_ATAC.sort.remap.fq2.gz
  /data/t2d-progenitor/ATAC-seq/PE_ATAC/PE_ATAC.sort.remap.single.fq.gz
  /data/t2d-progenitor/ATAC-seq/PE_ATAC/PE_ATAC.sort.keep.bam
  /data/t2d-progenitor/ATAC-seq/PE_ATAC/PE_ATAC.sort.to.remap.bam
starting chromosome chr1
reading SNPs from file '/data/t2d-progenitor/h5/snp_tab.h5'
reducing 344856 SNPs on chromosome chr1 to 214199 positions that are polymorphic in sample of 1 individuals
processing reads
Traceback (most recent call last):
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 930, in <module>
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 909, in main
    samples=samples)
  File "/lab/aaylward-shared/WASP/mapping/find_intersecting_snps.py", line 622, in filter_reads
    if read.next_reference_name is None:
AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'next_reference_name'
Closing remaining open files:/data/t2d-progenitor/h5/snp_index.h5...done/data/t2d-progenitor/h5/snp_tab.h5...done/data/t2d-progenitor/h5/haplotypes.h5...done
```
It seems some expected attribute of the data is not there? Could this be caused by missing information in my input BAM file?

**Comment by anthony-aylward** [comment]
Resolved this by updating pysam.
