### ISSUE TITLE
error in bam2h5 set_stats

### ISSUE THREAD

**Issue by sashagusev** [bmvdgeijn/WASP#53]
Hey guys, I'm having an issue with the latest master release ( f6e1d55 ) running bam2h5. After it goes through all of the chromosomes I get the following error:

```
setting statistics for each chromosome
Traceback (most recent call last):
  File "WASP/WASP-master/CHT/bam2h5.py", line 696, in <module>
    main()
  File "WASP/WASP-master/CHT/bam2h5.py", line 684, in main
    chromstat.set_stats(h5f, chrom_list)
  File "WASP/WASP-master/CHT/chromstat.py", line 100, in set_stats
    chrom_stat.set_from_vals(node[:])
  File "/home/ag284/.local/lib/python2.7/site-packages/tables/array.py", line 659, in __getitem__
    arr = self._read_slice(startl, stopl, stepl, shape)
  File "/home/ag284/.local/lib/python2.7/site-packages/tables/array.py", line 765, in _read_slice
    self._g_read_slice(startl, stopl, stepl, nparr)
  File "tables/hdf5extension.pyx", line 1522, in tables.hdf5extension.Array._g_read_slice (tables/hdf5extension.c:16883)
tables.exceptions.HDF5ExtError: HDF5 error back trace

  File "H5Dio.c", line 173, in H5Dread
    can't read data
  File "H5Dio.c", line 551, in H5D__read
    can't read data
  File "H5Dchunk.c", line 1875, in H5D__chunk_read
    unable to read raw data chunk
  File "H5Dchunk.c", line 2905, in H5D__chunk_lock
    data pipeline read failed
  File "H5Z.c", line 1372, in H5Z_pipeline
    filter returned failure during read
  File "H5Zdeflate.c", line 125, in H5Z_filter_deflate
    inflate() failed

End of HDF5 error back trace

Problems reading the array data.
Closing remaining open files

```

This is what I'm calling, and the BAM file was processed using the WASP re-mapping pipeline:

```
python $WASP_DIR/CHT/bam2h5.py \
--chrom $WASP_DIR/example_data/chromInfo.hg19.txt  \
--snp_index $CUR.snp_index.h5 \
--snp_tab   $CUR.snp_tab.h5 \
--haplotype $CUR.haps.h5 \
--samples IND \
--individual $IND \
--ref_as_counts $OUT.ref_as_counts.h5 \
--alt_as_counts $OUT.alt_as_counts.h5 \
--other_as_counts $OUT.other_as_counts.h5 \
--read_counts $OUT.read_counts.h5 \
$BAM
```

I do have some random contigs in the bam (chr17_ctg5_hap1, chrUn_gl000249, etc) and I get some CIGAR I/D errors while bam2h5 is running, could that be the issue?

Thanks for your help!

**Comment by gmcvicker** [comment]
Hi Sasha,
I am not sure what is causing this problem. My best guess is that your process ran out of memory. Another possibility is that you accidentally had two processes writing to the same HDF5 file at the same time so that the file became corrupted.  Can you try re-runnning (perhaps requesting more memory if your cluster allows you to specify this, and making sure you don't have two jobs writing to the same file) and let me know if you run into the same problem?

Thanks!
Graham

**Comment by sashagusev** [comment]
Good call, this was a file writing issue. Thanks for the quick diagnosis!
