### ISSUE TITLE
AttributeError: 'module' object has no attribute 'openFile'

### ISSUE THREAD

**Issue by MmXiaLin** [bmvdgeijn/WASP#59]
Hi Graham,

     I met a problem when I use the find_intersecting_snps.py. Could you please tell me how to fix it?

     command line: /home/WASP-master/mapping/find_intersecting_snps.py --is_paired_end --output_dir /home/Allele/test0228 --snp_index /home/Allele/test0228/genotypes/snp_index.h5 --snp_tab /home/Allele/test0228/genotypes/snp_tab.h5 --haplotype /home/Allele/test0228/genotypes/haps.h5 /home/Allele/test0228/2_14.bam
python version: 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2]
pysam version: 0.8.4
Traceback (most recent call last):
  File "/mnt/xdlab1/tools/WASP-master/mapping/find_intersecting_snps.py", line 954, in <module>
    samples=samples)
  File "/mnt/xdlab1/tools/WASP-master/mapping/find_intersecting_snps.py", line 927, in main
    haplotype_filename=haplotype_filename)
  File "/mnt/xdlab1/tools/WASP-master/mapping/find_intersecting_snps.py", line 67, in __init__
    self.snp_tab_h5 = tables.openFile(snp_tab_filename, "r")
AttributeError: 'module' object has no attribute 'openFile'

    And I had download tables-3.3.0 for python.

    Thank you so much!

**Comment by gmcvicker** [comment]
Hi, can you try to use an older version of PyTables (e.g. 2.4)? The recent versions of PyTables 3.x are no longer backwards compatible with the 2.x versions of PyTables and they have made many changes to the function names, as described here:
http://www.pytables.org/MIGRATING_TO_3.x.html

At some point we should create a new version of WASP that uses the most recent version of PyTables.

**Comment by MmXiaLin** [comment]
OK! Thank you so much! I will try to use the older version.

**Comment by KeyingLu** [comment]
Hi,
I met the same problem. Whether still need to use the old version of PyTables?
