### ISSUE TITLE
I need help please! 

### ISSUE THREAD

**Issue by olneykimberly** [bmvdgeijn/WASP#6]
I am on step two of mapping and I would like to know what version on python and pysam I should use because I keep getting errors 

$ python /Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/hg18_out/find_intersecting_snps.py -p /Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/hg18_out/accepted_hits.bam /Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/hg18_out/SNP_files 
Starting on chromosome chr1
Traceback (most recent call last):
  File "/Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/hg18_out/find_intersecting_snps.py", line 443, in <module>
    main()
  File "/Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/hg18_out/find_intersecting_snps.py", line 426, in main
    bam_data=Bam_scanner(options.is_paired_end,options.max_window,sort_file_name,keep_file_name,remap_name,remap_num_name,fastq_names,snp_dir)
  File "/Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/hg18_out/find_intersecting_snps.py", line 89, in __init__
    self.switch_chr()
  File "/Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/hg18_out/find_intersecting_snps.py", line 135, in switch_chr
    self.get_next_snp()
  File "/Users/olneykimberly/Desktop/TopHat/tophat-2.0.13.OSX_x86_64/hg18_out/find_intersecting_snps.py", line 182, in get_next_snp
    snp_line=self.snpfile.readline()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 436, in readline
    c = self.read(readsize)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 243, in read
    self._read(readsize)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 278, in _read
    self._read_gzip_header()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 174, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

Please Please help me! I'm going crazy with downloading and installing python and pysam and still it doesn't work :(

**Comment by bmvdgeijn** [comment]
I noticed that you closed the issue.  Did you figure out the problem?  If
you haven't, you should check that the SNP files you are using are
gzipped.  I think that this is where the IOError is coming from.  I'd be
happy to help if you run into any more issues.

Bryce

**Comment by olneykimberly** [comment]
Thank  you so much! and yes my snp files were not properly gzipped. Step two finished with no errors :) starting step three tomorrow.
